name: deployment-test
namespace: default
env:
  port: "8080"
image:
  repository: docker.io/baisnake/devops
  tag: latest
container:
  port: 8080
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  subnetId: test-subnet-ocid
secret:
  keyname: devops-registry-key
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50