name: deployment-test
namespace: default
env:
  port: "8080"
image:
  repository: https://hub.docker.com/repository/docker/baisnake/devops
  tag: latest
container:
  port: 8080
service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080
secret:
  keyname: devops-registry-key